### ISSUE TITLE
How can we print Android Formatting Superscript and Subscript

### ISSUE THREAD

**Issue by noelvillaman** [googlesamples/android-text#7]
This is what people accept as good in Stackoverflow ---> <sup><small>2</small></sup> S <sub><small>½</small></sub> <--- but that does not work for me. I literally copied this and the result was not a subscript.

Do you have any other way to do it?

Thanks,

**Comment by florina-muntenescu** [comment]
What do you mean with Formatting? Can you give more details and share the StackOverflow issue? 
Also, how do you copy it and where do you copy it? Are you creating Spans for styling the text?

**Comment by noelvillaman** [comment]
I copy paste the example given by people on stackoverflow. I create the
string and pull it from strings on my activity and nothing happens.

I want to be able to print X2, the nu never 2 in superscript form.

Noel.

**Comment by mohitajwani** [comment]
@noelvillaman I suggest you please check the [stackoverflow link](https://stackoverflow.com/questions/3543454/subscript-and-superscript-a-string-in-android).

There are multiple ways to do that,
1. You can load text from HTML
`((TextView)findViewById(R.id.text)).setText(Html.fromHtml("X<sup>2</sup>"));`
2. You can use Spans
```
equation = (TextView) findViewById(R.id.textView1);
SpannableStringBuilder cs = new SpannableStringBuilder("X3 + X2");
cs.setSpan(new SuperscriptSpan(), 1, 2, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
cs.setSpan(new RelativeSizeSpan(0.75f), 1, 2, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
cs.setSpan(new SuperscriptSpan(), 6, 7, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
cs.setSpan(new RelativeSizeSpan(0.75f), 6, 7, Spannable.SPAN_EXCLUSIVE_EXCLUSIVE);
equation.setText(cs);
```
Please correct me if I am wrong.

**Comment by florina-muntenescu** [comment]
A directly copy-pasted string will not work. You need to style it first, via `[SubscriptSpan](https://developer.android.com/reference/android/text/style/SubscriptSpan.html)` and `[SuperscriptSpan](https://developer.android.com/reference/android/text/style/SuperscriptSpan.html)`- these are classes from the Android framework. 
This project is not a library, it's a sample app, to showcase how to style text in Java and Kotlin

**Comment by noelvillaman** [comment]
private fun superscript() : SpannableStringBuilder{
    val text = "X2"
    val superscriptSpan = SuperscriptSpan()
    val builder = SpannableStringBuilder(text)
    builder.setSpan(
            superscriptSpan,
            text.indexOf("2"),
            text.indexOf("2") + "2".length,
            Spanned.SPAN_EXCLUSIVE_EXCLUSIVE)

    return builder
}

This function was taken from StackOverflow. I called on my textview, but it
still return the text as X2.

**Comment by noelvillaman** [comment]
I am sorry, this function does work, but only when I call it on its own,
without appending it to anything else.

**Comment by florina-muntenescu** [comment]
How are you appending it and how do you set the text in to the TextView?
