### ISSUE TITLE
The app should not crash during onCreate() (NPE: MainActivity.onCreate(MainActivity.java:48))

### ISSUE THREAD

**Issue by grigrom** [googlesamples/android-text#8]
The TextStyling-Java project build (on the top of c1663ac66ac103b8e2c130e74383895a3a4aa42d) crashes with the following stacktrace:

> com.android.example.text.styling E/AndroidRuntime: FATAL EXCEPTION: main
>  Process: com.android.example.text.styling, PID: 3843
>  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.example.text.styling/com.android.example.text.styling.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.FileDescriptor android.os.ParcelFileDescriptor.getFileDescriptor()' on a null object reference
>      …
>   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.io.FileDescriptor android.os.ParcelFileDescriptor.getFileDescriptor()' on a null object reference
>      at android.support.v4.graphics.TypefaceCompatUtil.mmap(TypefaceCompatUtil.java:98)
>      at android.support.v4.graphics.TypefaceCompatApi24Impl.createFromFontInfo(TypefaceCompatApi24Impl.java:140)
>      at android.support.v4.graphics.TypefaceCompat.createFromFontInfo(TypefaceCompat.java:167)
>      at android.support.v4.provider.FontsContractCompat.getFontInternal(FontsContractCompat.java:190)
>      at android.support.v4.provider.FontsContractCompat.getFontSync(FontsContractCompat.java:244)
>      at android.support.v4.graphics.TypefaceCompat.createFromResourcesFamilyXml(TypefaceCompat.java:124)
>      at android.support.v4.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:390)
>      at android.support.v4.content.res.ResourcesCompat.loadFont(ResourcesCompat.java:336)
>      at android.support.v4.content.res.ResourcesCompat.getFont(ResourcesCompat.java:205)
>      at com.android.example.text.styling.MainActivity.onCreate(MainActivity.java:48)
>      …

**Comment by florina-muntenescu** [comment]
This happens when you're trying to run an app that uses downloadable fonts on a device/emulator that doesn't have Google Play Services.
